### ISSUE TITLE
Website Title in SiteConfig is not Dynamic

### ISSUE THREAD

**Issue by surjithctly** [sanity-io/sanity-template-nextjs-ecommerce#8]
The website title is not queried in the code and its rendering as static. So can you add it as dynamic? 

Because I'm learning Sanity,.

**Comment by etuned** [comment]
This requires a lot of prop drilling which would introduce performance issues/unnecessary overhead  or a globally accessible query that is currently not supported with Next.js. I have been reading from core members of Next.js that using getStaticProps in _app is on the road map but I am no authority on it nor can I speak for them. Just know that you are not alone in wanting this feature. It will be possible in the future.

**Comment by surjithctly** [comment]
I was thinking, how does it work in its current way?

**Comment by etuned** [comment]
I guess I should ask to clarify. Do you mean the title displayed on the navbar? or the title displayed on the browser window?

If you are talking about the navbar as I thought you were.. then... 
The issue is that queries can only be fetched from the pages folders and not in components(the navbar being a component). The only component that wraps the whole application capable of sending props globally is _app. So we need this global scope because the navbar is a component rendered through the layout component which renders on each page that has different queries. You can run queries in _app but it will remove the auto dynamic optimized features of next.js. This stater takes advantage of next.js ability to render dynamically. So the only way to have a dynamic title render on the navbar from sanity (with this starter) is to make a query on each page and put the navbar on each of the pages or send the props multiple times. All ways lead to too many queries hurting performance. Once NextJs adds a way to make a global query without performance issues the title will be able to be dynamic on the navbar. For now it must be static.

If you are talking about the Title for the browser window then it's just a matter of adding next/head and rending the Head component with the title jsx tag with the title string from sanity. That will be no problem with no issue on performance at all. Hope this helps you and was clear.

**Comment by surjithctly** [comment]
Yes, I meant the Navbar only. 

If its just a page, not component, how would the query to the SiteTitle would look like? Coz, I'm new to Sanity & Groq. just wanted to see an example code on how this works.

**Comment by etuned** [comment]
The groq query to get the title of the site is the following for this starter:

*[_type == "siteConfig"][0]{title}

You then plug this into getStaticProps with the getClient wrapper from next-sanity or you can use the @sanity/client package. if you look at the index.js example in this starter the code would be as follows:

import Error from 'next/error'
import { groq } from 'next-sanity'
import LandingPage from '../components/LandingPage'
import { getClient, usePreviewSubscription } from '../utils/sanity'


const siteTitleQuery = groq`*[_type == "siteConfig"][0]{title}`
  {/* add another const with another query for page data */}

function IndexPage (props) {
const {title= 'Missing title'} = props

  return (
     <Wrapper>
    <Navbar>{title}</Navbar>
    {/* this is just for demo purposes but Github removes html tags, but add other elements here for page data in another query */}
    </Wrapper>
   );
}

export async function getStaticProps ({ params = {}, preview = false }) {
  const data = await getClient(preview).fetch(siteTitleQuery)
  {/* make one more separate getStaticProps function to grab page data  */}
  return {
    props: data
   }
   revalidate: 1, {/* this is for incremental build */}
}
 
export default IndexPage


Happy coding!

**Comment by etuned** [comment]
You very well could alter it to be a SPA to get what you want. Just make sure to use next image to get lazyloading for performant images.

**Comment by surjithctly** [comment]
Cool. That helps. Thank you.

**Comment by etuned** [comment]
Happy I could help.
